name: coastal_tourism_app
description: A mobile app for coastal tourism suitability.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0" # Updated SDK to a more recent version.

dependencies:
  flutter:
    sdk: flutter
  provider: any # Updated to the latest version.
  http: any  # Updated to the latest version.
  cupertino_icons: ^1.0.5  # Version 1.0.5 is the latest stable.
  flutter_riverpod: any # Updated to the latest version.
  google_maps_flutter: ^2.7.0  # The latest stable version.
  flutter_spinkit: ^5.2.1
  location: ^6.0.2
  font_awesome_flutter: ^10.7.0
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  cloud_firestore: ^4.5.3
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any  # Updated to the latest version.

flutter:
  uses-material-design: true