name: coastal_tourism_app
description: A mobile app for coastal tourism suitability.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0" # Updated SDK to a more recent version.

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5  # Updated to the latest version.
  http: ^0.15.0  # Updated to the latest version.
  cupertino_icons: ^1.0.5  # Version 1.0.5 is the latest stable.
  flutter_riverpod: ^2.6.1  # Updated to the latest version.
  google_maps_flutter: ^2.7.0  # The latest stable version.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.1.0  # Updated to the latest version.

flutter:
  uses-material-design: true
