name: coastal_tourism_app
description: A mobile app for coastal tourism suitability.

publish_to: null

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  http: ^1.2.1
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  google_maps_flutter: ^2.6.0
  flutter_spinkit: ^5.2.0
  cloud_firestore: ^4.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true